#!/bin/sh
# Generated by Pilot - manual provisioning script. Run every line as root, in order.
# target=local arch=amd64 steps=19
set -eu
# WARNING: TLS is off: the web client stays disabled and rustdesk.api-server is plain http, which keeps clients on ws://.
# WARNING: choices.openFirewall is off: Pilot applies no host firewall rules; open the required ports yourself.

# [1/19] Create the Pilot download cache
# Downloads are verified in a fixed directory so a re-run reuses them instead of refetching.
install -d -m 0755 /var/cache/pilot

# [2/19] Adopt the existing RustDesk server
# hbbs is already installed; Pilot records its public key and ports and never reinstalls or restarts it.
cat /var/lib/rustdesk-server/id_ed25519.pub

# [3/19] Download the API server 2.7 (amd64)
# The pinned release is fetched and checked against a recorded SHA256 before anything is unpacked.
curl -fsSL https://github.com/lejianwen/rustdesk-api/releases/download/v2.7/linux-amd64.tar.gz -o /var/cache/pilot/linux-amd64.tar.gz
printf '%s  %s\n' d0689a353fd756815cfe560ce7cb98f764602de60d0403b51db4e5a9bd84d22a /var/cache/pilot/linux-amd64.tar.gz | sha256sum -c -

# [4/19] Create /opt/rustdesk-api
# The API server runs from a fixed directory because its SQLite path is relative to the working directory.
install -d -m 0755 /opt/rustdesk-api

# [5/19] Create the rustdesk-api system user
# The API server must not run as root.
if ! id -u rustdesk-api >/dev/null 2>&1; then
useradd --system --home-dir /opt/rustdesk-api --shell /usr/sbin/nologin rustdesk-api
else
echo "skip: install-user (already satisfied)"
fi

# [6/19] Unpack the API server into /opt/rustdesk-api
# Every entry in the tarball is named ./release/<x>, so the two leading path components are stripped.
tar xzf /var/cache/pilot/linux-amd64.tar.gz -C /opt/rustdesk-api --strip-components=2

# [7/19] Confirm the API binary landed where the unit expects
# The unit execs /opt/rustdesk-api/apimain; if the archive layout ever changes, this is where it is caught.
test -x /opt/rustdesk-api/apimain

# [8/19] Create /opt/rustdesk-api/data
# The SQLite database is created at ./data/rustdeskapi.db relative to the working directory.
install -d -m 0750 /opt/rustdesk-api/data

# [9/19] Give rustdesk-api ownership of /opt/rustdesk-api
# The service writes its database, logs and runtime files under its own working directory.
chown -R rustdesk-api:rustdesk-api /opt/rustdesk-api

# [10/19] Create /opt/rustdesk-api/conf
# config.yaml is read from conf/ relative to the working directory.
install -d -m 0755 /opt/rustdesk-api/conf

# [11/19] Write /opt/rustdesk-api/conf/config.yaml
# This is where the hbbs id/relay servers, the server key and the API address are wired together.
install -d -m 0755 /opt/rustdesk-api/conf
cat > /opt/rustdesk-api/conf/config.yaml <<'PILOT_EOF_0'
# Generated by Pilot - do not edit by hand.
# Carries the release defaults: an omitted key is NOT inherited from
# the shipped config -- it takes Go's zero value, which has broken
# startup (resources-path) and login (captcha-threshold) before.
lang: "en"
app:
  web-client: 0
  register: false
  register-status: 1
  captcha-threshold: 3
  ban-threshold: 0
  show-swagger: 1
  token-expire: 8760h
  web-sso: true
  disable-pwd-login: false
admin:
  title: "RustDesk API Admin"
  hello-file: "./conf/admin/hello.html"
  id-server-port: 21116
  relay-server-port: 21117
gin:
  api-addr: 0.0.0.0:21114
  mode: "release"
  resources-path: 'resources'
  trust-proxy: ""
gorm:
  type: "sqlite"
  max-idle-conns: 10
  max-open-conns: 100
logger:
  path: "./runtime/log.txt"
  level: "info"
  report-caller: true
jwt:
  key: ""
  expire-duration: 8760h
proxy:
  enable: false
rustdesk:
  id-server: 203.0.113.10:21116
  relay-server: 203.0.113.10:21117
  api-server: http://203.0.113.10:21114
  personal: 1
  ws-host: ""
  key: "AbCdEf0123456789+/="
PILOT_EOF_0
chmod 0640 /opt/rustdesk-api/conf/config.yaml
chown rustdesk-api:rustdesk-api /opt/rustdesk-api/conf/config.yaml

# [12/19] Write /etc/systemd/system/rustdesk-api.service
# The unit pins WorkingDirectory=/opt/rustdesk-api, without which the database and log paths resolve to the wrong place.
install -d -m 0755 /etc/systemd/system
cat > /etc/systemd/system/rustdesk-api.service <<'PILOT_EOF_0'
[Unit]
Description=RustDesk API server (managed by Pilot)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=rustdesk-api
Group=rustdesk-api
WorkingDirectory=/opt/rustdesk-api
ExecStart=/opt/rustdesk-api/apimain
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
ProtectHome=true

[Install]
WantedBy=multi-user.target
PILOT_EOF_0
chmod 0644 /etc/systemd/system/rustdesk-api.service
chown root:root /etc/systemd/system/rustdesk-api.service

# [13/19] Reload the systemd unit files
# systemd will not see a newly written unit until it is told to reload.
systemctl daemon-reload

# [14/19] Enable rustdesk-api at boot
# Survives a reboot. This does NOT apply the unit and config just written.
systemctl enable rustdesk-api.service

# [15/19] Start rustdesk-api on the new configuration
# The unit and config.yaml were just rewritten; only a restart makes them take effect.
systemctl restart rustdesk-api.service

# [16/19] Confirm rustdesk-api is actually running
# enable --now reports success for a service that started and immediately died.
systemctl is-active --quiet rustdesk-api.service

# [17/19] List the ports the target is actually listening on
# The plan records what the target believes; the wizard then probes the same ports from the Cockpit host, which is what catches a cloud firewall.
ss -ltun

# [18/19] Wait for the API server to answer
# The Swagger document is served only because Pilot writes show-swagger: 1, so this proves both the service and the generated config. Probes the port the server is actually on: the already-running port when adopted, the chosen port when freshly installed.
curl -fsS --retry 10 --retry-delay 2 --retry-connrefused --max-time 60 -o /dev/null -w 'api answered HTTP %{http_code} in %{time_total}s' http://127.0.0.1:21114/admin/swagger/doc.json

# [19/19] Capture the generated admin password
# The API server prints its generated admin password once, into the journal.
# SECRET: this command is safe to run and safe to share - its OUTPUT contains a credential; do not paste the OUTPUT into a shared log.
journalctl -u rustdesk-api.service --no-pager -n 200

